apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-data
  namespace: ordersystem
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  local:
    path: /tmp/zookeeper-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
    
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-log
  namespace: ordersystem
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce  
  local:
    path: /tmp/zookeeper-log
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
