spring:
  application:
    name: order-service

  kafka:
    bootstrap-servers: ${KAFKA_SERVICE_URL}
    consumer:
      group-id: order-service-group
      auto-offset-reset: earliest
      
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver: ${SPRING_DATASOURCE_DRIVER}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        formate_sql: true
        
logging:
  level:
    org.apache.kafka: DEBUG