apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: ordersystem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: order-service:1.0.1  # Ersetze dies durch das Docker-Image deines Order Services
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_SERVICE_URL
              value: kafka.ordersystem.svc.cluster.local:9092
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/orderdb
            - name: SPRING_DATASOURCE_USERNAME
              value: orderuser
            - name: SPRING_DATASOURCE_PASSWORD
              value: orderpass
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: order-service
