apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: ordersystem
spec:
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None  # Headless für StatefulSet
  selector:
    app: postgres
